### PR TITLE
Always build before running tests so compiled JS is available for electron to run.

### PR DESCRIPTION
**Pull request by Mossop**

### CODE REVIEW

**Comment by Mossop** [comment]
This works so will let devs run end to end tests without packaging. We probably want to make CI run it against packages either instead of or as well though.

**Comment by joewalker** [comment]
On phone in YVR, so this is from memory, but I think we might be able to remove getBuiltExecutable now?

**Comment by Mossop** [comment]
I was going to leave it in so we could use it to run packaged builds in CI
in the future, I don't mind taking it out till then though

**Comment by joewalker** [comment]
I think that getBuiltExecutable is easy to write and feels a bit custom for a utility anyway, so I'd vote to remove it.
LGTM otherwise.

**Pull request merged**
