### PR TITLE
Eslint tests aren't run for .jsx files, fixes #66

### LINKED ISSUE #66: Eslint tests aren't run for .jsx files

### PR DESCRIPTION
**Pull request by victorporof**
Signed-off-by: Victor Porof <vporof@mozilla.com>

### CODE REVIEW

**Comment by victorporof** [comment]
https://github.com/mozilla/tofino/issues/66

**Comment by victorporof** [comment]
Review ping @joewalker

**Comment by victorporof** [comment]
Using `assignee` for pull requests to mark review requests.

**Comment by jsantell** [comment]
r+

**Pull request merged**
