### PR TITLE
Add ESLint rule: react/display-name. r=vporof

### PR DESCRIPTION
**Pull request by linclark**
This worked on local, but not exactly as expected. Going to see what CI does with it before landing #223 just to make sure it actually fails things correctly.

### CODE REVIEW

**Comment by linclark** [comment]
r? vporof

Even though this is red, I don't think it's the cause of the failures, so I think this is ready to land.

**Comment by victorporof** [comment]
r++!

**Comment by victorporof** [comment]
Do you prefer to land this yourself, or should I squash? I'm asking because I don't know whether or not the commits are there to help reviewing or because they're relevant history.

(As a team, we all have different opinions about this. Some people prefer squashing, some carefully organize their PRs into multiple relevant commits that should be part of history.)

**Comment by linclark** [comment]
I usually squash via the UI these days. I'll go ahead and do that.

**Pull request merged**
