### PR TITLE
Add coverage reporting. Fixes #114. r=jsantell

### LINKED ISSUE #114: Consider using Coveralls or some other way of tracking test coverage
It'd be nice tracking test coverage. It'd probably currently be a 1%, but that's more the reason to do it.
Cool kids seem to be using https://coveralls.io/. There might be other solutions too.

### PR DESCRIPTION
**Pull request by linclark**
@jsantell it's for real this time

### CODE REVIEW

**Comment by jsantell** [comment]
Looks good! Only change I'd say is using explicit versions for the dependencies (we don't yet have a good dependency upgrade story, so this will make those deps atleast consistent with the others)

**Comment by victorporof** [comment]
We should land this, yes?

**Comment by linclark** [comment]
I updated the PR to pin the dependencies. We may want to consider greenkeeper for dependency updates. I created #149 to discuss this.

Do we like the comments that coveralls is posting here? If not, I can disable them.

**Comment by victorporof** [comment]
I like 'em.

**Comment by jsantell** [comment]
Same! I guess we can merge this and deal with the account setup/hooks? Right now they're just on your branch, Lin, yeah? Should add a badge to README.md once we have that wired up!

**Comment by linclark** [comment]
I'm pretty sure that it will work on all Travis CI builds once it's merged. If it doesn't I'll look into it after the merge.

**Comment by victorporof** [comment]
Merging.

**Comment by jsantell** [comment]
@linclark oh nice! I thought it would've needed some account or something to set up, but this looks pretty great really, especially with the codecoverage diffing: https://github.com/mozilla/tofino/pull/150#issuecomment-211108380

**Pull request merged**
