### PR TITLE
Add pluralization to the number of pages indicator and some padding to the location bar

### PR DESCRIPTION
**Pull request by iDev0urer**
Signed-off-by: Christopher Watson <chris@marginzero.co>

### CODE REVIEW

**Comment by iDev0urer** [comment]
Oh and for sign-off purposes:

Signed-off-by: Christopher Watson <chris@marginzero.co>

**Comment by victorporof** [comment]
Looks good to me. Should really get out l10n story straight, soon.

**Comment by victorporof** [comment]
@iDev0urer Please sign off your commits before publishing. See https://github.com/mozilla/tofino/blob/master/CONTRIBUTING.md

**Comment by iDev0urer** [comment]
@victorporof Any way to do that after a commit has been made?

**Comment by victorporof** [comment]
Just do an incremental rebase on your branch and ammend commits at each step.

**Comment by victorporof** [comment]
Should probably add more of this info to the wiki.

**Comment by victorporof** [comment]
Added the info to the wiki. @iDev0urer feel free to check it out: https://github.com/mozilla/tofino/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
