### PR TITLE
Preliminary changes allowing sharing relevant code between browser frontends

### PR DESCRIPTION
**Pull request by victorporof**
Depends on https://github.com/mozilla/tofino/pull/1064

### CODE REVIEW

**Comment by bgrins** [comment]
The 'add tab' icon is missing with this applied

**Comment by bgrins** [comment]
There's propType warnings in https://travis-ci.org/mozilla/tofino/jobs/156845260

**Comment by victorporof** [comment]
@bgrins Fixed the `add tab` problem. The propType warnings were there before too.

**Comment by victorporof** [comment]
For some reason the builds are stalling at the end on CI. Will look into it, but everything else should be reviewable.

**Comment by bgrins** [comment]
The move looks fine to me, just make sure to figure out the CI failures before landing

**Pull request closed without merging**
