### PR TITLE
Update electron to 1.2.2

### PR DESCRIPTION
**Pull request by victorporof**
Signed-off-by: Victor Porof <vporof@mozilla.com>

Reopened from https://github.com/mozilla/tofino/pull/652

Turns out this needs to wait for a little longer.

### CODE REVIEW

**Comment by victorporof** [comment]
Fixes https://github.com/mozilla/tofino/issues/651

**Comment by bgrins** [comment]
Uploaded 1.2.2 for OSX, confirmed it's working locally

**Comment by victorporof** [comment]
Can this land?

**Comment by bgrins** [comment]
Landed

**Pull request merged**
