### PR TITLE
Start a REPL after launching the UA service.

### PR DESCRIPTION
**Pull request by rnewman**
After this you can run

```
./node_modules/.bin/babel-node lib/main/server.js
```

to get a REPL running the UA service.

### CODE REVIEW

**Comment by rnewman** [comment]
Something about the build config check has stopped working after your latest changes landed, @jsantell. Is the spawning stuff chewing up the environment?

**Comment by Mossop** [comment]
Can we add an "npm run ua" to start this?

**Comment by jsantell** [comment]
build-config shouldn't change based on process, what are you seeing?
If #565 looks good, maybe we can just roll this into another option (and then can expose either via `npm run ua` like @Mossop says)

**Comment by rnewman** [comment]
Perhaps it's down to how I'm invoking the process? The development check wasn't true.

And yes, @mossop, that'd be great.

I'll take a look at your PR after this fx-team call, @jsantell.

**Comment by rnewman** [comment]
Ah, we don't default to `development`. That'll do it. This'll rebase nicely on top of #565.

**Comment by jsantell** [comment]
Closed via 01d195dc140a9927dfc1d2fa669a283cab8c79aa

**Pull request closed without merging**
