### PR TITLE
Add CmdOrCtrl+R shortcut for page reload. Fixes #102. r=jsantell

### LINKED ISSUE #102: Add CmdOrCtrlR shortcut for page reload

### PR DESCRIPTION
**Pull request by gabrielluong**
#102 
r? @jsantell

### CODE REVIEW

**Comment by victorporof** [comment]
r+ from me if @jsantell can't get to it

**Comment by gabrielluong** [comment]
@victorporof, I changed the r to you. Feel free to land whenever.

**Comment by bgrins** [comment]
I think we should provide an alternative shortcut for the 'reload the app' behavior instead of just removing it.  What about CmdOrCtrl+Alt+R or CmdOrCtrl+Shift+R?

**Comment by victorporof** [comment]
@bgrins 👍 for CmdOrCtrl+Alt+R, since "alt" usually signifies alternate behavior.

**Pull request merged**
