### PR TITLE
Issue #63 - Fix electron version getter

### PR DESCRIPTION
**Pull request by gabrielluong**

### CODE REVIEW

**Comment by bgrins** [comment]
r+

**Comment by bgrins** [comment]
@gabrielluong will you please sign off on the commit as in https://github.com/mozilla/tofino/blob/master/CONTRIBUTING.md?

**Comment by victorporof** [comment]
This was failing travis: https://travis-ci.org/mozilla/tofino/builds/122307177

**Comment by victorporof** [comment]
From the discussion in https://github.com/mozilla/tofino/issues/63 apparently my changing of @bgrins's merge message caused travis to get confused. All is well, but I'm never force pushing ever again :)

**Pull request merged**
