### PR TITLE
Use class property initialization for binding. r=vporof

### LINKED ISSUE #605: Use class property initialization instead of binding in constructor
We can do this now that #554 has landed. I'm going to transition all of the existing instances of this so that its not inconsistent when I add new ones.

### PR DESCRIPTION
**Pull request by linclark**
Fixes #605

### CODE REVIEW

**Comment by linclark** [comment]
Didn't think about this before, but we could move propTypes and displayName definitions into the class with this too...

anyone have an opinion about that?

**Comment by victorporof** [comment]
🚢

**Comment by victorporof** [comment]
@linclark I have no strong preference either way.

**Comment by linclark** [comment]
ok, I'll just ship it as is. we can always switch that up later.

**Pull request merged**
